--------------------------------------------------------
--  Ref Constraints for Table ACC_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ACC_TRANSACTION" ADD CONSTRAINT "ACC_TRANSACTION_ACCOUNT_FK" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "ADMIN"."ACCOUNT" ("ACCOUNT_ID") ENABLE;
  ALTER TABLE "ADMIN"."ACC_TRANSACTION" ADD CONSTRAINT "ACC_TRANSACTION_BRANCH_FK" FOREIGN KEY ("EXECUTION_BRANCH_ID")
	  REFERENCES "ADMIN"."BRANCH" ("BRANCH_ID") ENABLE;
  ALTER TABLE "ADMIN"."ACC_TRANSACTION" ADD CONSTRAINT "ACC_TRANSACTION_EMPLOYEE_FK" FOREIGN KEY ("TELLER_EMP_ID")
	  REFERENCES "ADMIN"."EMPLOYEE" ("EMP_ID") ENABLE;
