--------------------------------------------------------
--  DDL for Table ACC_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ACC_TRANSACTION" 
   (	"TXN_ID" NUMBER(19,0), 
	"AMOUNT" FLOAT(126), 
	"FUNDS_AVAIL_DATE" TIMESTAMP (6), 
	"TXN_DATE" TIMESTAMP (6), 
	"TXN_TYPE_CD" VARCHAR2(10 CHAR), 
	"ACCOUNT_ID" NUMBER(10,0), 
	"EXECUTION_BRANCH_ID" NUMBER(10,0), 
	"TELLER_EMP_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
