--------------------------------------------------------
--  Constraints for Table ACC_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ACC_TRANSACTION" ADD PRIMARY KEY ("TXN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."ACC_TRANSACTION" MODIFY ("TXN_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACC_TRANSACTION" MODIFY ("FUNDS_AVAIL_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACC_TRANSACTION" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ACC_TRANSACTION" MODIFY ("TXN_ID" NOT NULL ENABLE);
