--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_BRANCH_FK" FOREIGN KEY ("OPEN_BRANCH_ID")
	  REFERENCES "ADMIN"."BRANCH" ("BRANCH_ID") ENABLE;
  ALTER TABLE "ADMIN"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_CUSTOMER_FK" FOREIGN KEY ("CUST_ID")
	  REFERENCES "ADMIN"."CUSTOMER" ("CUST_ID") ENABLE;
  ALTER TABLE "ADMIN"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_EMPLOYEE_FK" FOREIGN KEY ("OPEN_EMP_ID")
	  REFERENCES "ADMIN"."EMPLOYEE" ("EMP_ID") ENABLE;
  ALTER TABLE "ADMIN"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_PRODUCT_FK" FOREIGN KEY ("PRODUCT_CD")
	  REFERENCES "ADMIN"."PRODUCT" ("PRODUCT_CD") ENABLE;
