--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ACCOUNT" 
   (	"ACCOUNT_ID" NUMBER(10,0), 
	"AVAIL_BALANCE" FLOAT(126), 
	"CLOSE_DATE" DATE, 
	"LAST_ACTIVITY_DATE" DATE, 
	"OPEN_DATE" DATE, 
	"PENDING_BALANCE" FLOAT(126), 
	"STATUS" VARCHAR2(10 CHAR), 
	"CUST_ID" NUMBER(10,0), 
	"OPEN_BRANCH_ID" NUMBER(10,0), 
	"OPEN_EMP_ID" NUMBER(10,0), 
	"PRODUCT_CD" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
