--------------------------------------------------------
--  File created - Sunday-February-04-2018   
--------------------------------------------------------
@C:\testdb\HIBERNATE_SEQUENCE.sql
@C:\testdb\ACCOUNT.sql
@C:\testdb\ACC_TRANSACTION.sql
@C:\testdb\BRANCH.sql
@C:\testdb\BUSINESS.sql
@C:\testdb\CUSTOMER.sql
@C:\testdb\DEPARTMENT.sql
@C:\testdb\EMPLOYEE.sql
@C:\testdb\INDIVIDUAL.sql
@C:\testdb\OFFICER.sql
@C:\testdb\PRODUCT.sql
@C:\testdb\PRODUCT_TYPE.sql
@C:\testdb\ACCOUNT_DATA_TABLE.sql
@C:\testdb\ACC_TRANSACTION_DATA_TABLE.sql
@C:\testdb\BRANCH_DATA_TABLE.sql
@C:\testdb\BUSINESS_DATA_TABLE.sql
@C:\testdb\CUSTOMER_DATA_TABLE.sql
@C:\testdb\DEPARTMENT_DATA_TABLE.sql
@C:\testdb\EMPLOYEE_DATA_TABLE.sql
@C:\testdb\INDIVIDUAL_DATA_TABLE.sql
@C:\testdb\OFFICER_DATA_TABLE.sql
@C:\testdb\PRODUCT_DATA_TABLE.sql
@C:\testdb\PRODUCT_TYPE_DATA_TABLE.sql
@C:\testdb\DEPARTMENT_CONSTRAINT.sql
@C:\testdb\ACCOUNT_CONSTRAINT.sql
@C:\testdb\CUSTOMER_CONSTRAINT.sql
@C:\testdb\BUSINESS_CONSTRAINT.sql
@C:\testdb\OFFICER_CONSTRAINT.sql
@C:\testdb\INDIVIDUAL_CONSTRAINT.sql
@C:\testdb\PRODUCT_CONSTRAINT.sql
@C:\testdb\PRODUCT_TYPE_CONSTRAINT.sql
@C:\testdb\EMPLOYEE_CONSTRAINT.sql
@C:\testdb\BRANCH_CONSTRAINT.sql
@C:\testdb\ACC_TRANSACTION_CONSTRAINT.sql
@C:\testdb\ACCOUNT_REFCONSTRAINT.sql
@C:\testdb\ACC_TRANSACTION_REFCONSTRAINT.sql
@C:\testdb\BUSINESS_REFCONSTRAINT.sql
@C:\testdb\EMPLOYEE_REFCONSTRAINT.sql
@C:\testdb\INDIVIDUAL_REFCONSTRAINT.sql
@C:\testdb\OFFICER_REFCONSTRAINT.sql
@C:\testdb\PRODUCT_REFCONSTRAINT.sql
