--------------------------------------------------------
--  DDL for Table OFFICER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."OFFICER" 
   (	"OFFICER_ID" NUMBER(10,0), 
	"END_DATE" DATE, 
	"FIRST_NAME" VARCHAR2(30 CHAR), 
	"LAST_NAME" VARCHAR2(30 CHAR), 
	"START_DATE" DATE, 
	"TITLE" VARCHAR2(20 CHAR), 
	"CUST_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
